import { List, Products } from "./type";

export const dataProducts: Products = {
  products: [
    {
      id: 1,
      name: "Yaourt",
      quantity: 3,
      price: 500,
      status: true,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 2,
      name: "Lait",
      quantity: 2,
      price: 400,
      status: true,
      category: { id: 2, name: "Boisson" },
    },
    {
      id: 3,
      name: "Fromage",
      quantity: 1,
      price: 1200,
      status: false,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 4,
      name: "Beurre",
      quantity: 5,
      price: 800,
      status: true,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 5,
      name: "Crème",
      quantity: 2,
      price: 600,
      status: true,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 6,
      name: "Chips",
      quantity: 4,
      price: 300,
      status: true,
      category: { id: 3, name: "Snacks" },
    },
    {
      id: 7,
      name: "Jus d'orange",
      quantity: 6,
      price: 700,
      status: false,
      category: { id: 2, name: "Boisson" },
    },
    {
      id: 8,
      name: "Pomme",
      quantity: 10,
      price: 200,
      status: true,
      category: { id: 4, name: "Fruits" },
    },
    {
      id: 9,
      name: "Banane",
      quantity: 8,
      price: 150,
      status: true,
      category: { id: 4, name: "Fruits" },
    },
    {
      id: 10,
      name: "Pain",
      quantity: 3,
      price: 250,
      status: true,
      category: { id: 5, name: "Épicerie" },
    },
    {
      id: 11,
      name: "Lait",
      quantity: 4,
      price: 450,
      status: true,
      category: { id: 2, name: "Boisson" },
    },
    {
      id: 12,
      name: "Fromage",
      quantity: 2,
      price: 1300,
      status: false,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 13,
      name: "Yaourt",
      quantity: 5,
      price: 550,
      status: true,
      category: { id: 1, name: "Produit Laitier" },
    },
    {
      id: 14,
      name: "Chocolat",
      quantity: 7,
      price: 900,
      status: true,
      category: { id: 3, name: "Snacks" },
    },
    {
      id: 15,
      name: "Crème",
      quantity: 1,
      price: 650,
      status: true,
      category: { id: 1, name: "Produit Laitier" },
    },
  ],
  amount: 8450,
};

// data.ts
export const listsData: List[] = [
  {
    id: 1,
    title: "Facture électricité",
    date: "2025-09-01",
    amount: 120000,
  },
  {
    id: 2,
    title: "Achat courses",
    date: "2025-09-02",
    amount: 85000,
  },
  {
    id: 3,
    title: "Abonnement Internet",
    date: "2025-09-03",
    amount: 65000,
  },
  {
    id: 4,
    title: "Transport",
    date: "2025-09-04",
    amount: 30000,
  },
  {
    id: 5,
    title: "Restaurant",
    date: "2025-09-05",
    amount: 45000,
  },
  {
    id: 6,
    title: "Essence",
    date: "2025-09-06",
    amount: 60000,
  },
  {
    id: 7,
    title: "Internet mobile",
    date: "2025-09-07",
    amount: 25000,
  },
  {
    id: 8,
    title: "Abonnement gym",
    date: "2025-09-08",
    amount: 35000,
  },
  {
    id: 9,
    title: "Loisirs",
    date: "2025-09-09",
    amount: 40000,
  },
  {
    id: 10,
    title: "Divers",
    date: "2025-09-10",
    amount: 20000,
  },
];
