import type { Metadata } from "next";
import "./globals.css";
import Headers from "./_components/headers/Headers";

export const metadata: Metadata = {
  title: "Bazary",
  description: "Generated by create me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-poppins w-full h-full flex justify-center items-center`}
      >
        <main className="max-w-6xl md:h-screen h-full w-full relative pt-24">
          <Headers />
          {children}
        </main>
      </body>
    </html>
  );
}
