import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bazary",
  description: "Generated by create me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`antialiased font-poppins w-full h-full flex justify-center items-center bg-white dark:bg-dark`}
      >
        <main className="max-w-6xl md:h-screen h-full w-full relative pt-28 pb-2 ">
          {children}
        </main>
      </body>
    </html>
  );
}
